version: '3.7'

services:
  app:
    build:
      context: .
    container_name: mailing-list-api
    depends_on:
      - mailing-list-database
    volumes:
      - .:/home/node/app
    ports:
      - ${APP_PORT}:${APP_PORT}
      - ${APP_PORT_DEBUG}:${APP_PORT_DEBUG}
    networks:
      - mailing-list-network

  mailing-list-database:
    image: mongo
    container_name: mailing-list-database
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_USERNAME=${MONGO_USER}
      - MONGODB_PASSWORD=${MONGO_PASS}
      - MONGODB_DATABASE=${MONGO_DB}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mailing-list-data:/data/db
    networks:
      - mailing-list-network

volumes:
  mailing-list-data:
    driver: local

networks:
  mailing-list-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
